In [4]:
import numpy as np

import sys
if "../" not in sys.path:
  sys.path.append("../") 


In [22]:
from lib.envs.gridworld import GridworldEnv

만들어 놓았던 환경을 불러온다.

In [6]:
env = GridworldEnv()

In [33]:
#폴리시 이벨류에이션 함수 생성

def policy_eval(policy, env, discount_factor=1.0, theta=0.00001): #아규먼트는 폴리시, 환경, 디스카운트팩터, 세타값을 받는다
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
    폴리시 : 스테이트와 엑션으로 이루어진 메트릭스 
    엑션 : 오픈에이 아이의 환경,  env.P는 환경에서 트렌지션 확률을 의미한다.env.P[s][a] 은 (확률, 다음 스테이트, 리워드, 끝) 의 터플이다. 
    세타 : 관찰값의 변화가 이 세타값보다 작으면 멈춘다. 
    디스카운트펙터 -> 현재가 아닌 미래의 리워드의 기대값을 줄여주기  위한 하이퍼파라미터
    
    리턴: 
        벨류 함수를 나타내는 16개의 스테이트를 나타내는 벡터
    """
    
    #값이 0인 벨류함수로 시작
    

    V = np.zeros(env.nS) 
    
    
    
    while True:#While looping until True
        
        delta = 0 #델타값을 0으로 지정
        
        for s in range(env.nS): #모든 스테이트에서 ("full backup")
            
            v = 0 #벨류의 초기값은 0으로 설정
            # Look at the possible next actions
            for a, action_prob in enumerate(policy[s]): 
                
                
                #가능한 엑션과 그 엑션을 할 확률                
                for  prob, next_state, reward, done in env.P[s][a]: #env.P[s][a]에 들어있는 확률, 다음스테이트, 리워드, 끝을 포문으로 돌림
                    # 벨류값 계산
                    v += action_prob * prob * (reward + discount_factor * V[next_state])
            #value function이 얼마나 변했는지 계산
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v 
            
            print(V[s])
            
        # Stop evaluating once our value function change is below a threshold
        #정해놓은 세타값보다 delta가 작으면 멈춘다. 
         
        if delta < theta:
            break
    return np.array(V)

In [34]:


#0.25의 확률을 가지고 있는 엑션들을 생성
random_policy = np.ones([env.nS, env.nA]) / env.nA


v = policy_eval(random_policy, env)

0.0
-1.0
-1.25
-1.3125
-1.0
-1.5
-1.6875
-1.75
-1.25
-1.6875
-1.84375
-1.8984375
-1.3125
-1.75
-1.8984375
0.0
0.0
-1.9375
-2.546875
-2.73046875
-1.9375
-2.8125
-3.23828125
-3.404296875
-2.546875
-3.23828125
-3.568359375
-3.2177734375
-2.73046875
-3.404296875
-3.2177734375
0.0
0.0
-2.82421875
-3.8349609375
-4.17504882812
-2.82421875
-4.03125
-4.70971679688
-4.87670898438
-3.8349609375
-4.70971679688
-4.96374511719
-4.26455688477
-4.17504882812
-4.87670898438
-4.26455688477
0.0
0.0
-3.67260742188
-5.09808349609
-5.58122253418
-3.67260742188
-5.19116210938
-6.03242492676
-6.18872833252
-5.09808349609
-6.03242492676
-6.14849090576
-5.15044403076
-5.58122253418
-6.18872833252
-5.15044403076
0.0
0.0
-4.49046325684
-6.30054855347
-6.91293048859
-4.49046325684
-6.2614440918
-7.22480297089
-7.36922645569
-6.30054855347
-7.22480297089
-7.18762350082
-5.92682349682
-6.91293048859
-7.36922645569
-5.92682349682
0.0
0.0
-5.26311397552
-7.42534899712
-8.15510910749
-5.26311397552
-7.24395847321
-8.30

-21.9697198156
-13.9808641815
-17.9765178399
-19.9745037702
-19.9747953042
-19.9724897004
-19.9745037702
-17.9784858503
-13.9839372712
-21.9697198156
-19.9747953042
-13.9839372712
0.0
0.0
-13.9824679305
-19.9747953042
-21.9722575599
-13.9824679305
-17.9784858503
-19.9766405772
-19.9769076781
-19.9747953042
-19.9766405772
-17.9802889242
-13.9852834684
-21.9722575599
-19.9769076781
-13.9852834684
0.0
0.0
-13.9839372712
-19.9769076781
-21.974582619
-13.9839372712
-17.9802889242
-19.9785983012
-19.9788430167
-19.9769076781
-19.9785983012
-17.9819408848
-13.9865168425
-21.974582619
-19.9788430167
-13.9865168425
0.0
0.0
-13.9852834684
-19.9788430167
-21.9767128178
-13.9852834684
-17.9819408848
-19.9803919507
-19.9806161569
-19.9788430167
-19.9803919507
-17.9834543966
-13.987646849
-21.9767128178
-19.9806161569
-13.987646849
0.0
0.0
-13.9865168425
-19.9806161569
-21.9786644874
-13.9865168425
-17.9834543966
-19.9820352768
-19.9822406925
-19.9806161569
-19.9820352768
-17.9848410629
-13.98868215

In [32]:
print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

Value Function:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569   0.        ]

Reshaped Grid Value Function:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]

